theme: jekyll-theme-tactile
name: Pain NI Information Network
description: Common Ground for suffers of chronic pain

url: http://pain-ni.info
permalink: pretty
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
